harmony-one/harmony-ops

- devops/bin/devops.sh
- devops/bin/start_soldier.sh
Signed-off-by: Leo Chen <leo@harmony.one>
> add script to handle instance reboot case

- devops/find_duplicated_fn_keys/main.py
per Li's request, and I think it  should be part of QC for FN key swapping
> python script to find duplidated wallet addresses and bls keys

- monitoring/balance-monitoring/check.sh
Signed-off-by: Leo Chen <leo@harmony.one>
> [1h] use hmy cli to replace wallet in /1h page

- monitoring/bridge-monitor/bridge-watchdog/root.go
Add Google DNS http request to check for internet connection
Wrap bnbcli error to display exit status & output
> Bridge Monitor Update #3

- monitoring/bridge-monitor/bridge-watchdog/daemon-cmds.go
- monitoring/bridge-monitor/bridge-watchdog/root.go
Take expected total balance as input param
Update default expected tokens
> Bridge Monitor Update #4

- monitoring/harmony-monitor/blockchain-watchdog/root.go
yaml config file example:
```
node-distribution:
machine-ip-list:
- ./mainnet_shard0.txt
- ./mainnet_shard1.txt
- ./mainnet_shard2.txt
- ./mainnet_shard3.txt
```
> [Watchdog] Accept multiple files for ip list & read from all of them

- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
Add block num, epoch num & leader ip to shard summary at top
Remove unused code
> Watchdog improvements (#156)

- .gitignore
- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
Add .csv dump capabilities for block header & node metadara tables
Change .gitignore to reflect new binary name (harmony-watchdogd)
> Watchdog dump .csv files

- monitoring/harmony-monitor/blockchain-watchdog/daemon-cmds.go
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
- monitoring/harmony-monitor/blockchain-watchdog/root.go
observe usage of waitGroup, sync.Map
> [watchdog] Implement validate-ip-in-shard subcommand

- monitoring/harmony-monitor/README.md
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
- monitoring/harmony-monitor/blockchain-watchdog/root.go
@janet-harmony Please continue on this PR:
> Docs and index fix

- monitoring/harmony-monitor/README.md
- monitoring/harmony-monitor/blockchain-watchdog/daemon-cmds.go
- monitoring/harmony-monitor/blockchain-watchdog/root.go
Add command to print sample yaml command
Update README to reflect printed sample
Addresses #218
> [watchdog] Sample config file subcommand

- test-automation/api-tests/README.md
- test-automation/api-tests/localnet_test.sh
- test-automation/api-tests/test.py
* Added fast keys import as requested by @fxfactorial 
* Added logic that checks for duplicate keys (as different passphrases can cause errors)
* Update Readme and localnet test script.
> Add fast account import & fix possible duplicate key errors

- monitoring/bridge-monitor/bridge-watchdog/root.go
* Reduce refresh time to 5 min from 1 min
* Send 1 alert per difference
> [bridge-watch] Less PagerDuty spam when deviation hits threshold

- test-automation/api-tests/README.md
- test-automation/api-tests/test.py
Fix for testnet & devnet testing.
> Testing script, Fix after epoch check & update readme

- test-automation/api-tests/README.md
- test-automation/api-tests/test.py
> [staking-testing] Add base staking commands for testing

- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
* Consensus monitor uses its own pool of workers (only sends BlockHeader requests)
* Only processes data every 'warning' interval
Tested with locally with Localnet (shards down) & Mainnet.
> [watchdog] Separate data collections for Consensus Monitor & Watchdog display

- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
* Show shard that the node is on
* Add field for "role" of the node (ie. Explorer, Validator, Bootnode)
> [watchdog] Update NodeMetadata reports

- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
- monitoring/harmony-monitor/blockchain-watchdog/root.go
* Add ChainConfig display to the top of Watchdog report
* Improve mobile report display
* Add blocks per epoch stat
* Add consensus status to the chain config box
> #340 UI Improvements

- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
Please rebuild & restart watchdogs after squash merge
> [watchdog] space-between on row in stat boxes

- monitoring/uptimerobot.sh
Signed-off-by: Leo Chen <leo@harmony.one>
> [updatetime] use word search to find the monitor

- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
@janet-harmony can you please finish the pr by implementing the findLeaders function left undefined
> [watchdog] Sketch out find leaderIP for pagerduty report

- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
Reverts harmony-one/harmony-ops#360
> Revert "[watchdog] Sketch out find leaderIP for pagerduty report"

- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
- monitoring/harmony-monitor/blockchain-watchdog/root.go
- monitoring/harmony-monitor/blockchain-watchdog/rpc.go
[refactor] Pull RPC related structs into a separate file
> [watchdog] Add staking committee information to report page

- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
- monitoring/harmony-monitor/blockchain-watchdog/root.go
- monitoring/harmony-monitor/blockchain-watchdog/rpc.go
> [#394] Add route for network status summary /status-{network}

- monitoring/status-page/status/routes.py
> [status-page] Use longer names for network names

- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
1. Make element IDs in the committee section unique by using ShardID.
2. Add links pointing to the committee sections.
3. Hide links when there is no committee data.
> add links to shard committee sections

- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
closes #383 
1. Populate new shardMap Map with shardIDs keyed by their addresses (from superCommittee in monitor's update method).
2. Pass shardMap into manager and consensusMonitor methods.
3. Pass shardID into noReply slice.
4. Expose shardID in html template.
> add intended shardID to down machines

- devops/mini_explorer/mini_explorer.py
* Enable flag to run on mainnet (no staking transactions)
* Accept either string or file as input for endpoints
* Thread requests to decrease sleep timer
> [mini_explorer] Improvments

- devops/create_https_wss_endpoints_aws/main.py
$ python3 main.py -n testnet --update
or
$ python3 main.py -n testnet -u
> add a param to enable update endpoints targets only

- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
- monitoring/harmony-monitor/blockchain-watchdog/rpc.go
> [watchdog] Committees field name change in rpc

- devops/create_https_wss_endpoints_aws/helpers.py
- devops/create_https_wss_endpoints_aws/main.py
* create a helper file to keep common funcs
* improve update_target_groups such that it can handle the scenario when explorers are located in different regions
> Pr register explorers multiple regions

- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
Update SuperCommittee table
Update status report to include more information
> [watchdog] Update display & status information

- monitoring/status-page/networks.txt
- monitoring/status-page/status/routes.py
- monitoring/status-page/status/templates/status.html.j2
* Add Partner network to status page
* Add commit version (TODO: Make prettier)
* Add API endpoint query to status page (TODO: Kinda slow, need threading)
> [status-page] More features for status page

- monitoring/harmony-monitor/blockchain-watchdog/alerts.go
- monitoring/harmony-monitor/blockchain-watchdog/crosslink-monitor.go
- monitoring/harmony-monitor/blockchain-watchdog/daemon-cmds.go
- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
- monitoring/harmony-monitor/blockchain-watchdog/pager.go
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
- monitoring/harmony-monitor/blockchain-watchdog/root.go
- monitoring/harmony-monitor/blockchain-watchdog/rpc.go
[watchdog] Add monitor for processing cross links
[watchdog] Fix shard id for committee information
[watchdog] Fix used-seat count for status page
[refactor] One function for getting format for RPC requests
[refactor] Move PagerDuty notification messages into a separate file
> [#463] Add monitor for processing cross links 

- devops/create_https_wss_endpoints_aws/creation_elb2.py
- devops/create_https_wss_endpoints_aws/creation_entries.py
- devops/create_https_wss_endpoints_aws/main.py
* fixed route 53 update issue
* disabled -u functionality
> [feature] Route 53 update

- monitoring/status-page/status/routes.py
- monitoring/status-page/status/templates/status.html.j2
[status-page] Fix threading issues for faster loading
[status-page] Move version next to network name (harmony-#2491)
[status-page] Show total number of committee seats & used seats
> [status-page] Fix slow loading times

- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
- monitoring/harmony-monitor/blockchain-watchdog/rpc.go
> [watchdog] Update getNodeMetadata RPC

- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
- monitoring/harmony-monitor/blockchain-watchdog/root.go
[watchdog] Fix panic when ip list file not found
[watchdog] Add unique external validator count to status output
> [Watchdog] Addition for status page & minor fix

- monitoring/harmony-monitor/blockchain-watchdog/html-generators.go
- monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go
- monitoring/harmony-monitor/blockchain-watchdog/rpc.go
- monitoring/harmony-monitor/go.sum
Needs this PR to be merged/released on OSTN https://github.com/harmony-one/harmony/pull/2642
> [watchdog] Add external validator slot count

- devops/validator_stats/validator_stats.py
[validator_stats] Display information for new validators
[validator_stats] Add number of elected validators per group
Sample output:
```
-- Total Validator Stats --
Total created validators: 65
Validators that have earned rewards: 48
Current validators: 42
Total bls keys in committee: 90
-- Created Validators Per Group --
Group: team                 Number: 18
Group: p-ops                Number: 6
Group: foundational nodes   Number: 13
Group: community            Number: 12
Group: p-volunteer          Number: 6
Group: partners             Number: 1
Total: 56
-- Earned Validators Per Group --
Group: team                 Number: 12
Group: p-ops                Number: 6
Group: foundational nodes   Number: 12
Group: community            Number: 10
Group: p-volunteer          Number: 3
Group: …
```
> [validator_stats] New Validators & Elected Per Group

- devops/auto_node/run.py
- devops/auto_node/scripts/auto_node.sh
Needed for the automatic upgrade with node.ssh
> [auto_node] Fix (temp) node.sh for saved BLS passphrases

- devops/commit_logger/README.md
- devops/commit_logger/commit/__init__.py
- devops/commit_logger/commit/commit_logger.py
- devops/commit_logger/commit/routes.py
- devops/commit_logger/logger.py
- monitoring/status-page/status/routes.py
[commit_logger] Get commit version & max block height & timestamps for a network
[commit_logger] Flask server to serve output json
[commit_logger] Create back up of commit.json in case of data corruption
> Commit logging script

- devops/auto_node/Dockerfile
- devops/auto_node/run.py
- devops/auto_node/scripts/auto_node.sh
- devops/auto_node/scripts/balances.sh
- devops/auto_node/scripts/deactivate.sh
- devops/auto_node/scripts/headers.sh
- devops/auto_node/utils.py
Commands Added: `./autonode.sh balances` & `./autonode.sh deactivate` & `./autonode.sh headers`
Fixed export command and error on string for name fields.
> Improve node sync check of Auto Node + QOL commands

- devops/create_https_wss_endpoints_aws/creation_certificates.py
- devops/create_https_wss_endpoints_aws/creation_elb2.py
- devops/create_https_wss_endpoints_aws/creation_entries.py
- devops/create_https_wss_endpoints_aws/creation_listener.py
- devops/create_https_wss_endpoints_aws/creation_rule.py
- devops/create_https_wss_endpoints_aws/creation_tg.py
- devops/create_https_wss_endpoints_aws/helpers.py
- devops/create_https_wss_endpoints_aws/main.py
- devops/create_https_wss_endpoints_aws/registration_exps.py
1/ cleaned up duplicated ssl certs in 4 regions
2/ add logic not to request existing SSL certs
3/ code refactoring
4/ tested the pipeline on STN network
5/ dedicate aws user created for this task
TO-DO:
1/ need to add this user in devops instance, or not?
2/ Jenkins automation
> Avoid requesting duplicated SSL, and Code Refactoring

- devops/create_https_wss_endpoints_aws/creation_certificates.py
- devops/create_https_wss_endpoints_aws/creation_elb2.py
- devops/create_https_wss_endpoints_aws/creation_entries.py
- devops/create_https_wss_endpoints_aws/creation_listener.py
- devops/create_https_wss_endpoints_aws/creation_rule.py
- devops/create_https_wss_endpoints_aws/creation_tg.py
- devops/create_https_wss_endpoints_aws/helpers.py
- devops/create_https_wss_endpoints_aws/main.py
- devops/create_https_wss_endpoints_aws/registration_exps.py
- devops/create_https_wss_endpoints_aws/stn.json
CHANGES
1/ removed user-based permission control - more secure design
> remove user based permission control

- grafana/grafana_template/disk_io_count_template.json
- grafana/grafana_template/disk_space_template.json
- grafana/grafana_template/net_sock_tcp_template.json
- grafana/grafana_template/net_traffic_template.json
- grafana/grafana_template/ram_template.json
- grafana/prometheus_template/prometheus.yml
- grafana/update_db_config.py
1. split dashboard to base and network
2. add TCP socket stat metric
3. add disk IO count stat metric
> grafana add tcp metric and split dashboard

- grafana/grafana_template/dashboard_template.json
- grafana/update_db_config.py
optimize grafana dashboard theme and classify panel by dns/explorer/node type
> [grafana]classify panel by node type

- grafana/grafana_template/disk_space_template.json
- grafana/update_db_config.py
change `disk space` metric from free space size(GB) to used space rate(%), and set up alarm at `gt 90%`
> [grafana]change grafana disk metric

- grafana/grafana_template/ram_template.json
> grafana - update memory alert

- grafana/update_db_config.py
> [grafana] add two new services

- devops/elk/.env
- devops/elk/Makefile
- devops/elk/docker-compose.yml
- devops/elk/logstash.conf
see https://github.com/harmony-one/harmony/pull/4570
> ELK stack for runtime log processing.
